document.write("Hello Welcome to T-Max")
alert( 22 + 11 + "Goodbye")
let Fullname =( "Audu Linus Elachi")
console.log(Fullname)
let Stateoforigin = ("Hail from Okpokwu local govt area of Benue state, Nigeria.")
console.log(Stateoforigin)
let qualification = ("A computer scientist from Abubakar Tafawa Balwa Univrsity, Bauchi State. Nigria")
console.log(qualification)
let occupation = ("A Web designer| Database Adiminstrator| Software Engineer.")
console.log(occupation)
let skill =("Currently learning web development at Nerdsfatory, a program sponsored by Project T-Max")
console.log(skill)
let hobby = ("singing| playing football| soializing")
console.log(hobby)